//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KIRSmartAV.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KIRSmartAV.Localization.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate.
        /// </summary>
        internal static string ActivateText {
            get {
                return ResourceManager.GetString("ActivateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to active.
        /// </summary>
        internal static string ActiveText {
            get {
                return ResourceManager.GetString("ActiveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This feature is experimental. This feature only availiable in developing environment..
        /// </summary>
        internal static string AddElevationManifestText {
            get {
                return ResourceManager.GetString("AddElevationManifestText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t show program settings because there is opened form(s)..
        /// </summary>
        internal static string CantShowSettings {
            get {
                return ResourceManager.GetString("CantShowSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivate.
        /// </summary>
        internal static string DeactivateText {
            get {
                return ResourceManager.GetString("DeactivateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to deactive.
        /// </summary>
        internal static string DeactiveText {
            get {
                return ResourceManager.GetString("DeactiveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encode/decode process completed..
        /// </summary>
        internal static string EncodeDecodeCompletedText {
            get {
                return ResourceManager.GetString("EncodeDecodeCompletedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success..
        /// </summary>
        internal static string EncodeDecodeCompletedTitle {
            get {
                return ResourceManager.GetString("EncodeDecodeCompletedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select input and/or output files first!.
        /// </summary>
        internal static string ErrorFileNotSelectedText {
            get {
                return ResourceManager.GetString("ErrorFileNotSelectedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files not selected..
        /// </summary>
        internal static string ErrorFileNotSelectedTitle {
            get {
                return ResourceManager.GetString("ErrorFileNotSelectedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart this app with administrative privilege..
        /// </summary>
        internal static string ErrorNotElevatedText {
            get {
                return ResourceManager.GetString("ErrorNotElevatedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not elevated..
        /// </summary>
        internal static string ErrorNotElevatedTitle {
            get {
                return ResourceManager.GetString("ErrorNotElevatedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Present.
        /// </summary>
        internal static string ExistText {
            get {
                return ResourceManager.GetString("ExistText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        internal static string InstallText {
            get {
                return ResourceManager.GetString("InstallText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powerful antivirus engine to provide virus protection..
        /// </summary>
        internal static string KClamAV_Desc {
            get {
                return ResourceManager.GetString("KClamAV_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypt/decrypt your files using Base64 transformation..
        /// </summary>
        internal static string KCrypt_Desc {
            get {
                return ResourceManager.GetString("KCrypt_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harden your flashdrives from being infected by viruses..
        /// </summary>
        internal static string KCure_Desc {
            get {
                return ResourceManager.GetString("KCure_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KIRSmartAV.
        /// </summary>
        internal static string KIRSmartAVTitle {
            get {
                return ResourceManager.GetString("KIRSmartAVTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harden your computer from being infected by viruses that came from flashdrives..
        /// </summary>
        internal static string KProtect_Desc {
            get {
                return ResourceManager.GetString("KProtect_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhide files and folders that hidden by viruses..
        /// </summary>
        internal static string KUnhide_Desc {
            get {
                return ResourceManager.GetString("KUnhide_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore attribute.
        /// </summary>
        internal static string KUnhide_RepairAttribute {
            get {
                return ResourceManager.GetString("KUnhide_RepairAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t access libclamav. Antivirus capability disabled..
        /// </summary>
        internal static string LibclamavError {
            get {
                return ResourceManager.GetString("LibclamavError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing.
        /// </summary>
        internal static string MissingText {
            get {
                return ResourceManager.GetString("MissingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a flashdrive first!.
        /// </summary>
        internal static string NotifyDriveNotSelectedText {
            get {
                return ResourceManager.GetString("NotifyDriveNotSelectedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flashdrive not selected..
        /// </summary>
        internal static string NotifyDriveNotSelectedTitle {
            get {
                return ResourceManager.GetString("NotifyDriveNotSelectedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You just plugged new flashdrive..
        /// </summary>
        internal static string NotifyDrivePlugged {
            get {
                return ResourceManager.GetString("NotifyDrivePlugged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program will continue running on background..
        /// </summary>
        internal static string NotifyRunningBackground {
            get {
                return ResourceManager.GetString("NotifyRunningBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New flashdrive has plugged in and QuickFix has taken an action..
        /// </summary>
        internal static string QuickFixFinished {
            get {
                return ResourceManager.GetString("QuickFixFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to remove SafeChest folder? All of it&apos;s contents will be deleted..
        /// </summary>
        internal static string SafeChestDeletionText {
            get {
                return ResourceManager.GetString("SafeChestDeletionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm SafeChest uninstallation..
        /// </summary>
        internal static string SafeChestDeletionTitle {
            get {
                return ResourceManager.GetString("SafeChestDeletionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compiling engine....
        /// </summary>
        internal static string ScanCompileEngine {
            get {
                return ResourceManager.GetString("ScanCompileEngine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan completed. No virus detected..
        /// </summary>
        internal static string ScanCompletedNoVirus {
            get {
                return ResourceManager.GetString("ScanCompletedNoVirus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan completed. Some viruses detected..
        /// </summary>
        internal static string ScanCompletedViruses {
            get {
                return ResourceManager.GetString("ScanCompletedViruses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couting files and folders....
        /// </summary>
        internal static string ScanCountText {
            get {
                return ResourceManager.GetString("ScanCountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Libclamav encoutered an error. Scan aborted..
        /// </summary>
        internal static string ScanEngineError {
            get {
                return ResourceManager.GetString("ScanEngineError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning....
        /// </summary>
        internal static string ScaningStill {
            get {
                return ResourceManager.GetString("ScaningStill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing libclamav....
        /// </summary>
        internal static string ScanPrepareClamav {
            get {
                return ResourceManager.GetString("ScanPrepareClamav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading databases....
        /// </summary>
        internal static string ScanPrepareDatabase {
            get {
                return ResourceManager.GetString("ScanPrepareDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix completed..
        /// </summary>
        internal static string ScanRepairCompleted {
            get {
                return ResourceManager.GetString("ScanRepairCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixing....
        /// </summary>
        internal static string ScanRepairing {
            get {
                return ResourceManager.GetString("ScanRepairing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix.
        /// </summary>
        internal static string ScanRepairText {
            get {
                return ResourceManager.GetString("ScanRepairText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select path to scan!.
        /// </summary>
        internal static string ScanSelectPathText {
            get {
                return ResourceManager.GetString("ScanSelectPathText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start scan.
        /// </summary>
        internal static string ScanStartText {
            get {
                return ResourceManager.GetString("ScanStartText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virus object detected..
        /// </summary>
        internal static string ScanVirusDetected {
            get {
                return ResourceManager.GetString("ScanVirusDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string StartText {
            get {
                return ResourceManager.GetString("StartText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string StopText {
            get {
                return ResourceManager.GetString("StopText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add startup entry on registry..
        /// </summary>
        internal static string UnableChangeRegistryText {
            get {
                return ResourceManager.GetString("UnableChangeRegistryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall.
        /// </summary>
        internal static string UninstallText {
            get {
                return ResourceManager.GetString("UninstallText", resourceCulture);
            }
        }
    }
}
